from enum import Enum

class Countries(Enum):
    AFG = {"iso": "AFG", "name": "Afghanistan"}
    ALB = {"iso": "ALB", "name": "Albania"}
    DZA = {"iso": "DZA", "name": "Algeria"}
    AND = {"iso": "AND", "name": "Andorra"}
    AGO = {"iso": "AGO", "name": "Angola"}
    ATA = {"iso": "ATA", "name": "Antarctica"}
    ATG = {"iso": "ATG", "name": "Antigua and Barbuda"}
    ARG = {"iso": "ARG", "name": "Argentina"}
    ARM = {"iso": "ARM", "name": "Armenia"}
    AUS = {"iso": "AUS", "name": "Australia"}
    AUT = {"iso": "AUT", "name": "Austria"}
    AZE = {"iso": "AZE", "name": "Azerbaijan"}
    BHS = {"iso": "BHS", "name": "Bahamas"}
    BHR = {"iso": "BHR", "name": "Bahrain"}
    BGD = {"iso": "BGD", "name": "Bangladesh"}
    BRB = {"iso": "BRB", "name": "Barbados"}
    BLR = {"iso": "BLR", "name": "Belarus"}
    BEL = {"iso": "BEL", "name": "Belgium"}
    BLZ = {"iso": "BLZ", "name": "Belize"}
    BEN = {"iso": "BEN", "name": "Benin"}
    BTN = {"iso": "BTN", "name": "Bhutan"}
    BOL = {"iso": "BOL", "name": "Bolivia"}
    BIH = {"iso": "BIH", "name": "Bosnia and Herzegovina"}
    BWA = {"iso": "BWA", "name": "Botswana"}
    BRA = {"iso": "BRA", "name": "Brazil"}
    BRN = {"iso": "BRN", "name": "Brunei"}
    BGR = {"iso": "BGR", "name": "Bulgaria"}
    BFA = {"iso": "BFA", "name": "Burkina Faso"}
    BDI = {"iso": "BDI", "name": "Burundi"}
    CPV = {"iso": "CPV", "name": "Cabo Verde"}
    KHM = {"iso": "KHM", "name": "Cambodia"}
    CMR = {"iso": "CMR", "name": "Cameroon"}
    CAN = {"iso": "CAN", "name": "Canada"}
    CAF = {"iso": "CAF", "name": "Central African Republic"}
    TCD = {"iso": "TCD", "name": "Chad"}
    CHL = {"iso": "CHL", "name": "Chile"}
    CHN = {"iso": "CHN", "name": "China"}
    COL = {"iso": "COL", "name": "Colombia"}
    COM = {"iso": "COM", "name": "Comoros"}
    COG = {"iso": "COG", "name": "Congo"}
    COD = {"iso": "COD", "name": "Congo (DRC)"}
    CRI = {"iso": "CRI", "name": "Costa Rica"}
    CIV = {"iso": "CIV", "name": "Côte d'Ivoire"}
    HRV = {"iso": "HRV", "name": "Croatia"}
    CUB = {"iso": "CUB", "name": "Cuba"}
    CYP = {"iso": "CYP", "name": "Cyprus"}
    CZE = {"iso": "CZE", "name": "Czechia"}
    DNK = {"iso": "DNK", "name": "Denmark"}
    DJI = {"iso": "DJI", "name": "Djibouti"}
    DMA = {"iso": "DMA", "name": "Dominica"}
    DOM = {"iso": "DOM", "name": "Dominican Republic"}
    ECU = {"iso": "ECU", "name": "Ecuador"}
    EGY = {"iso": "EGY", "name": "Egypt"}
    SLV = {"iso": "SLV", "name": "El Salvador"}
    GNQ = {"iso": "GNQ", "name": "Equatorial Guinea"}
    ERI = {"iso": "ERI", "name": "Eritrea"}
    EST = {"iso": "EST", "name": "Estonia"}
    ETH = {"iso": "ETH", "name": "Ethiopia"}
    FJI = {"iso": "FJI", "name": "Fiji"}
    FIN = {"iso": "FIN", "name": "Finland"}
    FRA = {"iso": "FRA", "name": "France"}
    GAB = {"iso": "GAB", "name": "Gabon"}
    GMB = {"iso": "GMB", "name": "Gambia"}
    GEO = {"iso": "GEO", "name": "Georgia"}
    DEU = {"iso": "DEU", "name": "Germany"}
    GHA = {"iso": "GHA", "name": "Ghana"}
    GRC = {"iso": "GRC", "name": "Greece"}
    GRD = {"iso": "GRD", "name": "Grenada"}
    GTG = {"iso": "GTM", "name": "Guatemala"}
    GIN = {"iso": "GIN", "name": "Guinea"}
    GNB = {"iso": "GNB", "name": "Guinea-Bissau"}
    GUY = {"iso": "GUY", "name": "Guyana"}
    HTI = {"iso": "HTI", "name": "Haiti"}
    VAT = {"iso": "VAT", "name": "Holy See"}
    HONd = {"iso": "HND", "name": "Honduras"}
    HUN = {"iso": "HUN", "name": "Hungary"}
    ISL = {"iso": "ISL", "name": "Iceland"}
    IND = {"iso": "IND", "name": "India"}
    IDN = {"iso": "IDN", "name": "Indonesia"}
    IRN = {"iso": "IRN", "name": "Iran"}
    IRQ = {"iso": "IRQ", "name": "Iraq"}
    IRL = {"iso": "IRL", "name": "Ireland"}
    ISR = {"iso": "ISR", "name": "Israel"}
    ITA = {"iso": "ITA", "name": "Italy"}
    JAM = {"iso": "JAM", "name": "Jamaica"}
    JPN = {"iso": "JPN", "name": "Japan"}
    JOR = {"iso": "JOR", "name": "Jordan"}
    KAZ = {"iso": "KAZ", "name": "Kazakhstan"}
    KEN = {"iso": "KEN", "name": "Kenya"}
    KIR = {"iso": "KIR", "name": "Kiribati"}
    PRK = {"iso": "PRK", "name": "North Korea"}
    KOR = {"iso": "KOR", "name": "South Korea"}
    KWT = {"iso": "KWT", "name": "Kuwait"}
    KGZ = {"iso": "KGZ", "name": "Kyrgyzstan"}
    LAO = {"iso": "LAO", "name": "Laos"}
    LVA = {"iso": "LVA", "name": "Latvia"}
    LBN = {"iso": "LBN", "name": "Lebanon"}
    LSO = {"iso": "LSO", "name": "Lesotho"}
    LBR = {"iso": "LBR", "name": "Liberia"}
    LBY = {"iso": "LBY", "name": "Libya"}
    LIE = {"iso": "LIE", "name": "Liechtenstein"}
    LTU = {"iso": "LTU", "name": "Lithuania"}
    LUX = {"iso": "LUX", "name": "Luxembourg"}
    MDG = {"iso": "MDG", "name": "Madagascar"}
    MWL = {"iso": "MWI", "name": "Malawi"}
    MYS = {"iso": "MYS", "name": "Malaysia"}
    MDV = {"iso": "MDV", "name": "Maldives"}
    MLI = {"iso": "MLI", "name": "Mali"}
    MLT = {"iso": "MLT", "name": "Malta"}
    MUS = {"iso": "MUS", "name": "Mauritius"}
    MAR = {"iso": "MAR", "name": "Mauritania"}
    MEX = {"iso": "MEX", "name": "Mexico"}
    MDA = {"iso": "MDA", "name": "Moldova"}
    MCO = {"iso": "MCO", "name": "Monaco"}
    MNG = {"iso": "MNG", "name": "Mongolia"}
    MNE = {"iso": "MNE", "name": "Montenegro"}
    MOZ = {"iso": "MOZ", "name": "Mozambique"}
    MMR = {"iso": "MMR", "name": "Myanmar"}
    NAM = {"iso": "NAM", "name": "Namibia"}
    NRU = {"iso": "NRU", "name": "Nauru"}
    NPL = {"iso": "NPL", "name": "Nepal"}
    NLD = {"iso": "NLD", "name": "Netherlands"}
    NZL = {"iso": "NZL", "name": "New Zealand"}
    NIC = {"iso": "NIC", "name": "Nicaragua"}
    NER = {"iso": "NER", "name": "Niger"}
    NGA = {"iso": "NGA", "name": "Nigeria"}
    MKD = {"iso": "MKD", "name": "North Macedonia"}
    NOR = {"iso": "NOR", "name": "Norway"}
    OMN = {"iso": "OMN", "name": "Oman"}
    PAK = {"iso": "PAK", "name": "Pakistan"}
    PLW = {"iso": "PLW", "name": "Palau"}
    PSE = {"iso": "PSE", "name": "Palestine"}
    PAN = {"iso": "PAN", "name": "Panama"}
    PNG = {"iso": "PNG", "name": "Papua New Guinea"}
    PRY = {"iso": "PRY", "name": "Paraguay"}
    PER = {"iso": "PER", "name": "Peru"}
    PHL = {"iso": "PHL", "name": "Philippines"}
    POL = {"iso": "POL", "name": "Poland"}
    PRT = {"iso": "PRT", "name": "Portugal"}
    QAT = {"iso": "QAT", "name": "Qatar"}
    ROU = {"iso": "ROU", "name": "Romania"}
    RUS = {"iso": "RUS", "name": "Russia"}
    RWA = {"iso": "RWA", "name": "Rwanda"}
    KNA = {"iso": "KNA", "name": "Saint Kitts and Nevis"}
    LCA = {"iso": "LCA", "name": "Saint Lucia"}
    VCT = {"iso": "VCT", "name": "Saint Vincent and the Grenadines"}
    WSM = {"iso": "WSM", "name": "Samoa"}
    SMR = {"iso": "SMR", "name": "San Marino"}
    STP = {"iso": "STP", "name": "Sao Tome and Principe"}
    SAU = {"iso": "SAU", "name": "Saudi Arabia"}
    SEN = {"iso": "SEN", "name": "Senegal"}
    SRB = {"iso": "SRB", "name": "Serbia"}
    SYC = {"iso": "SYC", "name": "Seychelles"}
    SLE = {"iso": "SLE", "name": "Sierra Leone"}
    SGP = {"iso": "SGP", "name": "Singapore"}
    SVK = {"iso": "SVK", "name": "Slovakia"}
    SVN = {"iso": "SVN", "name": "Slovenia"}
    SLB = {"iso": "SLB", "name": "Solomon Islands"}
    SOM = {"iso": "SOM", "name": "Somalia"}
    ZAF = {"iso": "ZAF", "name": "South Africa"}
    SSD = {"iso": "SSD", "name": "South Sudan"}
    ESP = {"iso": "ESP", "name": "Spain"}
    LKA = {"iso": "LKA", "name": "Sri Lanka"}
    SDN = {"iso": "SDN", "name": "Sudan"}
    SUR = {"iso": "SUR", "name": "Suriname"}
    SWE = {"iso": "SWE", "name": "Sweden"}
    CHE = {"iso": "CHE", "name": "Switzerland"}
    SYR = {"iso": "SYR", "name": "Syria"}
    TJK = {"iso": "TJK", "name": "Tajikistan"}
    TZA = {"iso": "TZA", "name": "Tanzania"}
    THA = {"iso": "THA", "name": "Thailand"}
    TGO = {"iso": "TGO", "name": "Togo"}
    TON = {"iso": "TON", "name": "Tonga"}
    TTO = {"iso": "TTO", "name": "Trinidad and Tobago"}
    TUN = {"iso": "TUN", "name": "Tunisia"}
    TUR = {"iso": "TUR", "name": "Turkey"}
    TKM = {"iso": "TKM", "name": "Turkmenistan"}
    TUV = {"iso": "TUV", "name": "Tuvalu"}
    UGA = {"iso": "UGA", "name": "Uganda"}
    UKR = {"iso": "UKR", "name": "Ukraine"}
    ARE = {"iso": "ARE", "name": "United Arab Emirates"}
    GBR = {"iso": "GBR", "name": "United Kingdom"}
    USA = {"iso": "USA", "name": "United States"}
    URY = {"iso": "URY", "name": "Uruguay"}
    UZB = {"iso": "UZB", "name": "Uzbekistan"}
    VUT = {"iso": "VUT", "name": "Vanuatu"}
    VEN = {"iso": "VEN", "name": "Venezuela"}
    VNM = {"iso": "VNM", "name": "Vietnam"}
    YEM = {"iso": "YEM", "name": "Yemen"}
    ZMB = {"iso": "ZMB", "name": "Zambia"}
    ZWE = {"iso": "ZWE", "name": "Zimbabwe"}