COUNTRIES = {
    "afg": {"iso": "AFG", "name": "Afghanistan"},
    "alb": {"iso": "ALB", "name": "Albania"},
    "dza": {"iso": "DZA", "name": "Algeria"},
    "and": {"iso": "AND", "name": "Andorra"},
    "ago": {"iso": "AGO", "name": "Angola"},
    "ata": {"iso": "ATA", "name": "Antarctica"},
    "atg": {"iso": "ATG", "name": "Antigua and Barbuda"},
    "arg": {"iso": "ARG", "name": "Argentina"},
    "arm": {"iso": "ARM", "name": "Armenia"},
    "aus": {"iso": "AUS", "name": "Australia"},
    "aut": {"iso": "AUT", "name": "Austria"},
    "aze": {"iso": "AZE", "name": "Azerbaijan"},
    "bhs": {"iso": "BHS", "name": "Bahamas"},
    "bhr": {"iso": "BHR", "name": "Bahrain"},
    "bgd": {"iso": "BGD", "name": "Bangladesh"},
    "brb": {"iso": "BRB", "name": "Barbados"},
    "blr": {"iso": "BLR", "name": "Belarus"},
    "bel": {"iso": "BEL", "name": "Belgium"},
    "blz": {"iso": "BLZ", "name": "Belize"},
    "ben": {"iso": "BEN", "name": "Benin"},
    "btn": {"iso": "BTN", "name": "Bhutan"},
    "bol": {"iso": "BOL", "name": "Bolivia"},
    "bih": {"iso": "BIH", "name": "Bosnia and Herzegovina"},
    "bwa": {"iso": "BWA", "name": "Botswana"},
    "bra": {"iso": "BRA", "name": "Brazil"},
    "brn": {"iso": "BRN", "name": "Brunei"},
    "bgr": {"iso": "BGR", "name": "Bulgaria"},
    "bfa": {"iso": "BFA", "name": "Burkina Faso"},
    "bdi": {"iso": "BDI", "name": "Burundi"},
    "cpv": {"iso": "CPV", "name": "Cabo Verde"},
    "khm": {"iso": "KHM", "name": "Cambodia"},
    "cmr": {"iso": "CMR", "name": "Cameroon"},
    "can": {"iso": "CAN", "name": "Canada"},
    "caf": {"iso": "CAF", "name": "Central African Republic"},
    "tcd": {"iso": "TCD", "name": "Chad"},
    "chl": {"iso": "CHL", "name": "Chile"},
    "chn": {"iso": "CHN", "name": "China"},
    "col": {"iso": "COL", "name": "Colombia"},
    "com": {"iso": "COM", "name": "Comoros"},
    "cog": {"iso": "COG", "name": "Congo"},
    "cod": {"iso": "COD", "name": "Congo (DRC)"},
    "cri": {"iso": "CRI", "name": "Costa Rica"},
    "civ": {"iso": "CIV", "name": "Côte d'Ivoire"},
    "hrv": {"iso": "HRV", "name": "Croatia"},
    "cub": {"iso": "CUB", "name": "Cuba"},
    "cyp": {"iso": "CYP", "name": "Cyprus"},
    "cze": {"iso": "CZE", "name": "Czechia"},
    "dnk": {"iso": "DNK", "name": "Denmark"},
    "dji": {"iso": "DJI", "name": "Djibouti"},
    "dma": {"iso": "DMA", "name": "Dominica"},
    "dom": {"iso": "DOM", "name": "Dominican Republic"},
    "ecu": {"iso": "ECU", "name": "Ecuador"},
    "egy": {"iso": "EGY", "name": "Egypt"},
    "slv": {"iso": "SLV", "name": "El Salv,ador"},
    "gnq": {"iso": "GNQ", "name": "Equator,ial Gu,inea"},
    "eri": {"iso": "ERI", "name": "Eritrea,"},
    "est": {"iso": "EST", "name": "Estonia,"},
    "eth": {"iso": "ETH", "name": "Ethiopi,a"},
    "fji": {"iso": "FJI", "name": "Fiji"},
    "fin": {"iso": "FIN", "name": "Finland"},
    "fra": {"iso": "FRA", "name": "France"},
    "gab": {"iso": "GAB", "name": "Gabon"},
    "gmb": {"iso": "GMB", "name": "Gambia"},
    "geo": {"iso": "GEO", "name": "Georgia"},
    "deu": {"iso": "DEU", "name": "Germany"},
    "gha": {"iso": "GHA", "name": "Ghana"},
    "grc": {"iso": "GRC", "name": "Greece"},
    "grd": {"iso": "GRD", "name": "Grenada"},
    "gtg": {"iso": "GTM", "name": "Guatemala"},
    "gin": {"iso": "GIN", "name": "Guinea"},
    "gnb": {"iso": "GNB", "name": "Guinea-Bissau,"},
    "guy": {"iso": "GUY", "name": "Guyana"},
    "hti": {"iso": "HTI", "name": "Haiti"},
    "vat": {"iso": "VAT", "name": "Holy See"},
    "hnd": {"iso": "HND", "name": "Honduras"},
    "hun": {"iso": "HUN", "name": "Hungary"},
    "isl": {"iso": "ISL", "name": "Iceland"},
    "ind": {"iso": "IND", "name": "India"},
    "idn": {"iso": "IDN", "name": "Indonesia"},
    "irn": {"iso": "IRN", "name": "Iran"},
    "irq": {"iso": "IRQ", "name": "Iraq"},
    "irl": {"iso": "IRL", "name": "Ireland"},
    "isr": {"iso": "ISR", "name": "Israel"},
    "ita": {"iso": "ITA", "name": "Italy"},
    "jam": {"iso": "JAM", "name": "Jamaica"},
    "jpn": {"iso": "JPN", "name": "Japan"},
    "jor": {"iso": "JOR", "name": "Jordan"},
    "kaz": {"iso": "KAZ", "name": "Kazakhstan"},
    "ken": {"iso": "KEN", "name": "Kenya"},
    "kir": {"iso": "KIR", "name": "Kiribati"},
    "prk": {"iso": "PRK", "name": "North Korea"},
    "kor": {"iso": "KOR", "name": "South Korea"},
    "kwt": {"iso": "KWT", "name": "Kuwait"},
    "kgz": {"iso": "KGZ", "name": "Kyrgyzstan"},
    "lao": {"iso": "LAO", "name": "Laos"},
    "lva": {"iso": "LVA", "name": "Latvia"},
    "lbn": {"iso": "LBN", "name": "Lebanon"},
    "lso": {"iso": "LSO", "name": "Lesotho"},
    "lbr": {"iso": "LBR", "name": "Liberia"},
    "lby": {"iso": "LBY", "name": "Libya"},
    "lie": {"iso": "LIE", "name": "Liechtenstein",},
    "ltu": {"iso": "LTU", "name": "Lithuania"},
    "lux": {"iso": "LUX", "name": "Luxembourg"},
    "mdg": {"iso": "MDG", "name": "Madagascar"},
    "mwl": {"iso": "MWI", "name": "Malawi"},
    "mys": {"iso": "MYS", "name": "Malaysia"},
    "mdv": {"iso": "MDV", "name": "Maldives"},
    "mli": {"iso": "MLI", "name": "Mali"},
    "mlt": {"iso": "MLT", "name": "Malta"},
    "mus": {"iso": "MUS", "name": "Mauritius"},
    "mar": {"iso": "MAR", "name": "Mauritania"},
    "mex": {"iso": "MEX", "name": "Mexico"},
    "mda": {"iso": "MDA", "name": "Moldova"},
    "mco": {"iso": "MCO", "name": "Monaco"},
    "mng": {"iso": "MNG", "name": "Mongolia"},
    "mne": {"iso": "MNE", "name": "Montenegro"},
    "moz": {"iso": "MOZ", "name": "Mozambique"},
    "mmr": {"iso": "MMR", "name": "Myanmar"},
    "nam": {"iso": "NAM", "name": "Namibia"},
    "nru": {"iso": "NRU", "name": "Nauru"},
    "npl": {"iso": "NPL", "name": "Nepal"},
    "nld": {"iso": "NLD", "name": "Netherlands"},
    "nzl": {"iso": "NZL", "name": "New Zealand"},
    "nic": {"iso": "NIC", "name": "Nicaragua"},
    "ner": {"iso": "NER", "name": "Niger"},
    "nga": {"iso": "NGA", "name": "Nigeria"},
    "mkd": {"iso": "MKD", "name": "North Macedoni,a"},
    "nor": {"iso": "NOR", "name": "Norway"},
    "omn": {"iso": "OMN", "name": "Oman"},
    "pak": {"iso": "PAK", "name": "Pakistan"},
    "plw": {"iso": "PLW", "name": "Palau"},
    "pse": {"iso": "PSE", "name": "Palestine"},
    "pan": {"iso": "PAN", "name": "Panama"},
    "png": {"iso": "PNG", "name": "Papua New Guin,ea"},
    "pry": {"iso": "PRY", "name": "Paraguay"},
    "per": {"iso": "PER", "name": "Peru"},
    "phl": {"iso": "PHL", "name": "Philippines"},
    "pol": {"iso": "POL", "name": "Poland"},
    "prt": {"iso": "PRT", "name": "Portugal"},
    "qat": {"iso": "QAT", "name": "Qatar"},
    "rou": {"iso": "ROU", "name": "Romania"},
    "rus": {"iso": "RUS", "name": "Russia"},
    "rwa": {"iso": "RWA", "name": "Rwanda"},
    "kna": {"iso": "KNA", "name": "Saint Kitts and Nevis"},
    "lca": {"iso": "LCA", "name": "Saint Lucia"},
    "vct": {"iso": "VCT", "name": "Saint Vincent, and the Grenadines"},
    "wsm": {"iso": "WSM", "name": "Samoa"},
    "smr": {"iso": "SMR", "name": "San Marino"},
    "stp": {"iso": "STP", "name": "Sao Tome and ,Principe"},
    "sau": {"iso": "SAU", "name": "Saudi Arabia",},
    "sen": {"iso": "SEN", "name": "Senegal"},
    "srb": {"iso": "SRB", "name": "Serbia"},
    "syc": {"iso": "SYC", "name": "Seychelles"},
    "sle": {"iso": "SLE", "name": "Sierra Leone",},
    "sgp": {"iso": "SGP", "name": "Singapore"},
    "svk": {"iso": "SVK", "name": "Slovakia"},
    "svn": {"iso": "SVN", "name": "Slovenia"},
    "slb": {"iso": "SLB", "name": "Solomon Islan,ds"},
    "som": {"iso": "SOM", "name": "Somalia"},
    "zaf": {"iso": "ZAF", "name": "South Africa",},
    "ssd": {"iso": "SSD", "name": "South Sudan"},
    "esp": {"iso": "ESP", "name": "Spain"},
    "lka": {"iso": "LKA", "name": "Sri Lanka"},
    "sdn": {"iso": "SDN", "name": "Sudan"},
    "sur": {"iso": "SUR", "name": "Suriname"},
    "swe": {"iso": "SWE", "name": "Sweden"},
    "che": {"iso": "CHE", "name": "Switzerland"},
    "syr": {"iso": "SYR", "name": "Syria"},
    "tjk": {"iso": "TJK", "name": "Tajikistan"},
    "tza": {"iso": "TZA", "name": "Tanzania"},
    "tha": {"iso": "THA", "name": "Thailand"},
    "tgo": {"iso": "TGO", "name": "Togo"},
    "ton": {"iso": "TON", "name": "Tonga"},
    "tto": {"iso": "TTO", "name": "Trinidad and ,Tobago"},
    "tun": {"iso": "TUN", "name": "Tunisia"},
    "tur": {"iso": "TUR", "name": "Turkey"},
    "tkm": {"iso": "TKM", "name": "Turkmenistan",},
    "tuv": {"iso": "TUV", "name": "Tuvalu"},
    "uga": {"iso": "UGA", "name": "Uganda"},
    "ukr": {"iso": "UKR", "name": "Ukraine"},
    "are": {"iso": "ARE", "name": "United Arab E,mirates"},
    "gbr": {"iso": "GBR", "name": "United Kingdo,m"},
    "usa": {"iso": "USA", "name": "United States,"},
    "ury": {"iso": "URY", "name": "Uruguay"},
    "uzb": {"iso": "UZB", "name": "Uzbekistan"},
    "vut": {"iso": "VUT", "name": "Vanuatu"},
    "ven": {"iso": "VEN", "name": "Venezuela"},
    "vnm": {"iso": "VNM", "name": "Vietnam"},
    "yem": {"iso": "YEM", "name": "Yemen"},
    "zmb": {"iso": "ZMB", "name": "Zambia"},
    "zwe": {"iso": "ZWE", "name": "Zimbabwe"}
}